In [1]:
import numpy as np
import pandas as pd

In [2]:
s=pd.Series([10,20,30,40,50])

In [3]:
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

Custom Index

In [4]:
s=pd.Series([10,20,30],index=['a','b','c'])

In [5]:
print(s)

a    10
b    20
c    30
dtype: int64

In [6]:
print(s["a"])

10

Series From Dictionary

In [7]:
data={"Math":90,"Science":80,"English":85}

In [8]:
print(data)

{'Math': 90, 'Science': 80, 'English': 85}

DataFrame in Pandas

In [9]:
data={"Name":["Aman","Ravi","Sita"],"Age":[20,22,19],"City":["Delhi","Mumbai","Bangalore"]}

In [10]:
print(data)

{'Name': ['Aman', 'Ravi', 'Sita'], 'Age': [20, 22, 19], 'City': ['Delhi', 'Mumbai', 'Bangalore']}

In [11]:
type(data)

dict

In [12]:
marks=pd.DataFrame(data)

In [13]:
print(marks)

   Name  Age       City
0  Aman   20      Delhi
1  Ravi   22     Mumbai
2  Sita   19  Bangalore

In [14]:
marks=pd.DataFrame(data,index=['Student1','Student2','Student3'])

In [15]:
print(marks)

          Name  Age       City
Student1  Aman   20      Delhi
Student2  Ravi   22     Mumbai
Student3  Sita   19  Bangalore

In [16]:
marks.set_index('Name',inplace=True) # Set 'Name' column as index and modify the DataFrame in place

In [17]:
print(marks)

      Age       City
Name
Aman   20      Delhi
Ravi   22     Mumbai
Sita   19  Bangalore

In [18]:
df=pd.DataFrame({"Name":["Aman","Karan","Sita"],"Age":[20,22,19],"Marks":["80","85","90"]})

In [19]:
df

    Name  Age Marks
0   Aman   20    80
1  Karan   22    85
2   Sita   19    90

In [20]:
df.head(2)

    Name  Age Marks
0   Aman   20    80
1  Karan   22    85

In [21]:
df.tail(2)

    Name  Age Marks
1  Karan   22    85
2   Sita   19    90

In [22]:
df.shape

(3, 3)

In [23]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Marks   3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [25]:
df.describe()

             Age
count   3.000000
mean   20.333333
std     1.527525
min    19.000000
25%    19.500000
50%    20.000000
75%    21.000000
max    22.000000

Selecting the Data

In [26]:
df["Name"]

0     Aman
1    Karan
2     Sita
Name: Name, dtype: str

In [27]:
df[["Name","Marks"]]

    Name Marks
0   Aman    80
1  Karan    85
2   Sita    90

Filtering in Pandas

In [28]:
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")
df[df["Marks"]>80]

    Name  Age  Marks
1  Karan   22     85
2   Sita   19     90

In [29]:
#Multple Condition
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df[(df["Age"]>21) & (df["Marks"]>80)]

    Name  Age  Marks
1  Karan   22     85

Sorting +Value Counts

In [30]:
df.sort_values("Marks")

    Name  Age  Marks
0   Aman   20     80
1  Karan   22     85
2   Sita   19     90

In [31]:
df.sort_values("Marks",ascending=False)

    Name  Age  Marks
2   Sita   19     90
1  Karan   22     85
0   Aman   20     80

In [32]:
df["Age"].value_counts()

Age
20    1
22    1
19    1
Name: count, dtype: int64