In [1]:
import pandas as pd
df=pd.read_csv('weather_data.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [8]:
weather_data={
    'day':['1/1/2020','1/2/2020','1/3/2020','1/4/2020','1/5/2020'],
    'temperature':[32,35,28,24,31],
    'windspeed':[6,7,2,4,5],
    'event':['Rain','Sunny','Snow','Cloudy','Rain']
}
df=pd.DataFrame(weather_data)
df

        day  temperature  windspeed   event
0  1/1/2020           32          6    Rain
1  1/2/2020           35          7   Sunny
2  1/3/2020           28          2    Snow
3  1/4/2020           24          4  Cloudy
4  1/5/2020           31          5    Rain

In [10]:
df.shape

(5, 4)

In [12]:
df.head(2)

        day  temperature  windspeed  event
0  1/1/2020           32          6   Rain
1  1/2/2020           35          7  Sunny

In [13]:
df.tail(2)

        day  temperature  windspeed   event
3  1/4/2020           24          4  Cloudy
4  1/5/2020           31          5    Rain

In [14]:
df[2:5]

        day  temperature  windspeed   event
2  1/3/2020           28          2    Snow
3  1/4/2020           24          4  Cloudy
4  1/5/2020           31          5    Rain

In [16]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='str')

In [18]:
df['event']

0      Rain
1     Sunny
2      Snow
3    Cloudy
4      Rain
Name: event, dtype: str

In [19]:
type(df['event'])

pandas.Series

In [20]:
df

        day  temperature  windspeed   event
0  1/1/2020           32          6    Rain
1  1/2/2020           35          7   Sunny
2  1/3/2020           28          2    Snow
3  1/4/2020           24          4  Cloudy
4  1/5/2020           31          5    Rain

In [22]:
df[['event','day']]

    event       day
0    Rain  1/1/2020
1   Sunny  1/2/2020
2    Snow  1/3/2020
3  Cloudy  1/4/2020
4    Rain  1/5/2020

In [23]:
df

        day  temperature  windspeed   event
0  1/1/2020           32          6    Rain
1  1/2/2020           35          7   Sunny
2  1/3/2020           28          2    Snow
3  1/4/2020           24          4  Cloudy
4  1/5/2020           31          5    Rain

In [25]:
df['temperature'].max()

np.int64(35)

In [27]:
df["temperature"].min()

np.int64(24)

In [28]:
df["temperature"].mean()

np.float64(30.0)

In [29]:
df.describe()

       temperature  windspeed
count       5.0000   5.000000
mean       30.0000   4.800000
std         4.1833   1.923538
min        24.0000   2.000000
25%        28.0000   4.000000
50%        31.0000   5.000000
75%        32.0000   6.000000
max        35.0000   7.000000

In [30]:
df[df.temperature>=32]

        day  temperature  windspeed  event
0  1/1/2020           32          6   Rain
1  1/2/2020           35          7  Sunny

In [31]:
df[df.temperature==df.temperature.max()]

        day  temperature  windspeed  event
1  1/2/2020           35          7  Sunny

In [32]:
df[['day','temperature']][df.temperature==df.temperature.max()]

        day  temperature
1  1/2/2020           35

In [33]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [41]:
df = pd.read_csv('weather_data.csv')
df.set_index('day',inplace=True)
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [43]:
df.loc['1/3/2017']

temperature      28
windspeed         2
event          Snow
Name: 1/3/2017, dtype: object

In [44]:
df.reset_index(inplace=True)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [45]:
df.set_index('event',inplace=True)
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [46]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7